### ISSUE TITLE
Conda env create

### ISSUE THREAD

**Issue by MaskXman** [clear-nus/edc#1]
Sorry , I can' t find a environment.yaml. I want to run your code ,Could you please provide this file?
Thank you.

**Comment by bzhangj13zzz** [comment]
Hi, the environment file is uploaded now. Please let me know if there's any further issue.

**Comment by MaskXman** [comment]
Thank you very much！！！！

---- Replied Message ----
| From | Bowen ***@***.***> |
| Date | 05/07/2024 23:28 |
| To | clear-nus/edc ***@***.***> |
| Cc | Maskman ***@***.***>,
Author ***@***.***> |
| Subject | Re: [clear-nus/edc] Conda env create (Issue #1) |

Hi, the environment file is uploaded now. Please let me know if there's any further issue.
