### ISSUE TITLE
算力

### ISSUE THREAD

**Issue by fireSunset** [clear-nus/edc#11]
![image](https://github.com/user-attachments/assets/5e21f7fa-e289-45ec-9e0a-0c6385792bcb)
![image](https://github.com/user-attachments/assets/57894d1b-6235-4e10-8926-474805a3795e)
代码对算力的基本要求是多少啊，换成rebel实验室三张GPU都不够

**Comment by fireSunset** [comment]
![image](https://github.com/user-attachments/assets/65fc8196-527c-49ab-96d8-d92669933e8f)

我尝试把模型下载到服务器，试了一下用api都直接报错，还是环境有问题吗=-=


from transformers import AutoTokenizer, AutoModelForCausalLM, GenerationConfig
import torch



def creat_step_model():
    model_name = '/home/lww/edc/model/Mistral-7B-Instruct-v0.2'
    model = AutoModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float16)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model.generation_config = GenerationConfig.from_pretrained(model_name)
    model.generation_config.max_new_tokens = 300
    tokenizer.pad_token = tokenizer.eos_token
    return model, tokenizer



device = "cuda:1"


model, tokenizer = creat_step_model()
model.to(device)

while(True):
    prompt = input("input：")
    inputs = tokenizer.encode(prompt, return_tensors="pt")
    outputs = model.generate(inputs.to(model.device))
    answers = tokenizer.decode(outputs[0])
    print(answers)

**Comment by fireSunset** [comment]
好奇怪鹅鹅鹅，我通过镜像下载模型之后，我的镜像网站也没法使用了，访问不了

**Comment by fireSunset** [comment]
换成Qwen2-0.5B-Instruct都不够，推理怎么会这么大，我都没有换数据，哭

**Comment by bzhangj13zzz** [comment]
应该是embedding model 太大了，是7B的mistral，我们之前试过用小的sentence transformer也可以有还行的性能，你可以试着改一下代码看看。

我这几天比较忙，过几天把代码重构一下，方便一下在架构里更换不同的模型

**Comment by fireSunset** [comment]
感谢感谢，那我等等吧=3=

**Comment by bzhangj13zzz** [comment]
Hi! 我们已经更新了代码，现在schema canonicalization和refinement都支持使用[sentence transformer](sbert.net)了，可以使用小模型来试一下
