### ISSUE TITLE
Run Time Error

### ISSUE THREAD

**Issue by Wonder947** [clear-nus/edc#12]
Hi,

I downloaded the system, did conda env set up and necessary env vars set up. And I tried to run the program on my
WSL2 Ubuntu in VSCode with the following command:

python run.py \
    --oie_llm gpt-3.5-turbo \
    --oie_few_shot_example_file_path
./few_shot_examples/webnlg/oie_few_shot_examples.txt \
    --sd_llm gpt-3.5-turbo \
    --sd_few_shot_example_file_path
./few_shot_examples/webnlg/sd_few_shot_examples.txt \
    --sc_llm gpt-3.5-turbo \
    --input_text_file_path ./datasets/webnlg.txt \
    --enrich_schema \
    --output_dir ./output/webnlg_self_canonicalization

But it then gives me logs with such error:

{'oie_llm': 'gpt-3.5-turbo', 'oie_prompt_template_file_path':
'./prompt_templates/oie_template.txt',
'oie_few_shot_example_file_path':
'./few_shot_examples/webnlg/oie_few_shot_examples.txt', 'sd_llm':
'gpt-3.5-turbo', 'sd_prompt_template_file_path':
'./prompt_templates/sd_template.txt', 'sd_few_shot_example_file_path':
'./few_shot_examples/webnlg/sd_few_shot_examples.txt', 'sc_llm':
'gpt-3.5-turbo', 'sc_prompt_template_file_path':
'./prompt_templates/sc_template.txt', 'sr_adapter_path': None,
'oie_refine_prompt_template_file_path':
'./prompt_templates/oie_r_template.txt',
'oie_refine_few_shot_example_file_path':
'./few_shot_examples/default/oie_few_shot_refine_examples.txt',
'ee_llm': 'mistralai/Mistral-7B-Instruct-v0.2',
'ee_prompt_template_file_path': './prompt_templates/ee_template.txt',
'ee_few_shot_example_file_path':
'./few_shot_examples/default/ee_few_shot_examples.txt',
'em_prompt_template_file_path': './prompt_templates/em_template.txt',
'input_text_file_path': './datasets/webnlg.txt', 'target_schema_path':
None, 'refinement_iterations': 0, 'enrich_schema': True, 'output_dir':
'./output/webnlg_self_canonicalization'}
Models used: {'mistralai/Mistral-7B-Instruct-v0.2', 'gpt-3.5-turbo'}
Loading models...
Loading checkpoint shards:
100%|███████████████████████████████████████████████████████████████████████████████████████████████████|
3/3 [00:14<00:00,  4.75s/it]
WARNING:root:Some parameters are on the meta device device because
they were offloaded to the disk and cpu.
Loading checkpoint shards:
100%|████████████████████████████████████████████████████████████████████████████████████████████████|
2/2 [00:00<00:00, 77672.30it/s]
Traceback (most recent call last):
  File "/mnt/c/users/947/desktop/nyu/research/Knowledge
Graph/Experiments/edc/run.py", line 106, in <module>
    edc = EDC(**args)
  File "/mnt/c/users/947/desktop/nyu/research/Knowledge
Graph/Experiments/edc/edc/edc_framework.py", line 94, in __init__
    schema_canonicalization_embedding_model =
MistralForSequenceEmbedding.from_pretrained(
  File "/home/wonder/anaconda3/envs/edc/lib/python3.9/site-packages/transformers/modeling_utils.py",
line 3904, in from_pretrained
    dispatch_model(model, **device_map_kwargs)
  File "/home/wonder/anaconda3/envs/edc/lib/python3.9/site-packages/accelerate/big_modeling.py",
line 490, in dispatch_model
    raise ValueError(
ValueError: You are trying to offload the whole model to the disk.
Please use the `disk_offload` function instead.

I'm wondering if I should change your code implementation of the edc_framework.py, or is it something related to my operation or
environmental settings?

**Comment by bzhangj13zzz** [comment]
Thank you for posting this issue. I believe this error happens due to insufficient GPU memory. We are currently working on a refactor that allows users to use smaller models. I will let you know once it is released. Thanks!

**Comment by bzhangj13zzz** [comment]
Hi! We have just updated our code，now schema canonicalization and refinement both support using [sentence transformer](https://github.com/clear-nus/edc/issues/sbert.net), you may try running EDC with smaller models.
