### ISSUE TITLE
Can edc use other embedding tokenizer

### ISSUE THREAD

**Issue by hanw** [clear-nus/edc#3]
`intfloat/e5-mistral-7b-instruct` is hard-coded in edc_framework.py, can it be replaced by other embedding model?

**Comment by bzhangj13zzz** [comment]
Yes, but we only tested with this model which is the state-of-the-art embedding model, I would recommend checking out sentence transformers. https://sbert.net/ It may also solve the memory issues as these models are much much smaller.
